name: 'Deploy'
description: 'Deploys current Maven project to Github Packages and OSSRH'
inputs:
    actor:
        descripton: 'The Github user that initiated the action'
        required: true
        default: ${{ github.actor }}
    token:
        description: 'The access token for the repository'
        required: true
        default: ${{ github.token }}
    gpg_private_key:
        description: 'Private key to sign artifacts with'
        required: true
    gpg_passphrase:
        description: 'Passphrase of the GPG private key'
        required: true
    nexus_username:
        description: 'Username of target Nexus'
        required: true
    nexus_password:
        description: 'Password of target Nexus'
        required: true
  
runs:
    using: "composite"
    steps: 
        - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
            java-version: 11
            gpg-private-key: ${{ inputs.gpg_private_key }} # Value of the GPG private key to import
            gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase
            
        - name: Build with Maven
        run: mvn clean package -B -P deploy

        - name: Publish to GitHub Packages
        run: mvn deploy -B -P deploy,github
        env:
            GITHUB_ACTOR: ${{ inputs.actor }}
            GITHUB_TOKEN: ${{ inputs.token }} 
            GPG_PASSPHRASE: ${{ inputs.gpg_passphrase }}

        - name: Set up Apache Maven Central
        uses: actions/setup-java@v1
        with: # running setup-java again overwrites the settings.xml
            java-version: 11
            server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
            server-username: NEXUS_USERNAME # env variable for username in deploy
            server-password: NEXUS_PASSWORD # env variable for token in deploy
            gpg-private-key: ${{ inputs.gpg_private_key }} # Value of the GPG private key to import
            gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase

        - name: Publish to OSSRH
        run: mvn deploy -B -P deploy,ossrh
        env:
            NEXUS_USERNAME: ${{ inputs.nexus_username }}
            NEXUS_PASSWORD: ${{ inputs.nexus_password }}
            GPG_PASSPHRASE: ${{ inputs.gpg_passphrase }}